# Generated by Django 3.2.20 on 2024-01-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
