# Generated by Django 3.2.20 on 2024-01-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(blank=True, help_text='Enter time in 24-hour format (e.g., 09:00 - 17:00)', max_length=50, verbose_name='Monday')),
                ('tuesday', models.CharField(blank=True, help_text='Enter time in 24-hour format (e.g., 09:00 - 17:00)', max_length=50, verbose_name='Tuesday')),
                ('wednesday', models.CharField(blank=True, help_text='Enter time in 24-hour format (e.g., 09:00 - 17:00)', max_length=50, verbose_name='Wednesday')),
                ('thursday', models.CharField(blank=True, help_text='Enter time in 24-hour format (e.g., 09:00 - 17:00)', max_length=50, verbose_name='Thursday')),
                ('friday', models.CharField(blank=True, help_text='Enter time in 24-hour format (e.g., 09:00 - 17:00)', max_length=50, verbose_name='Friday')),
                ('saturday', models.CharField(blank=True, help_text='Enter time in 24-hour format (e.g., 09:00 - 17:00)', max_length=50, verbose_name='Saturday')),
                ('sunday', models.CharField(blank=True, help_text='Enter time in 24-hour format (e.g., 09:00 - 17:00)', max_length=50, verbose_name='Sunday')),
            ],
            options={
                'verbose_name_plural': 'Opening Hours',
            },
        ),
    ]
